/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable, tap } from 'rxjs';
import { EventFileDTO } from '../model/eventFileDTO';
import { environment } from '../../../environments/environment.local';

@Injectable({
  providedIn: 'root'
})
export class EventFileControllerService {
  private baseUrl = `${environment.host}/api/v1/events`;

  constructor(private http: HttpClient) { }

  /**
   * Uploader un fichier pour un événement
   * @param eventId Identifiant de l'événement
   * @param file Fichier à uploader
   * @param description Description optionnelle du fichier
   * @returns Observable<EventFileDTO>
   */
  uploadEventFile(eventId: string, file: File, description?: string): Observable<EventFileDTO> {
    const formData = new FormData();
    formData.append('file', file);
    if (description) {
      formData.append('description', description);
    }
    
    return this.http.post<EventFileDTO>(`${this.baseUrl}/${eventId}/files/upload`, formData);
  }

  /**
   * Uploader plusieurs fichiers pour un événement
   * @param eventId Identifiant de l'événement
   * @param files Tableau de fichiers à uploader
   * @param descriptions Descriptions optionnelles des fichiers
   * @returns Observable<EventFileDTO[]>
   */
  uploadMultipleEventFiles(eventId: string, files: File[], descriptions?: string[]): Observable<EventFileDTO[]> {
    const formData = new FormData();
    files.forEach((file, index) => {
      formData.append('files', file);
      if (descriptions && descriptions[index]) {
        formData.append('descriptions', descriptions[index]);
      }
    });
    
    return this.http.post<EventFileDTO[]>(`${this.baseUrl}/${eventId}/files/upload-multiple`, formData);
  }

  /**
   * Récupérer tous les fichiers d'un événement
   * @param eventId Identifiant de l'événement
   * @returns Observable<EventFileDTO[]>
   */
  getEventFiles(eventId: string): Observable<EventFileDTO[]> {
    const url = `${this.baseUrl}/${eventId}/files`;
    console.log('=== EventFileControllerService.getEventFiles (API) ===');
    console.log('Event ID:', eventId);
    console.log('Base URL:', this.baseUrl);
    console.log('URL complète:', url);
    console.log('Environment host:', environment.host);
    console.log('Environment object:', environment);
    
    return this.http.get<EventFileDTO[]>(url).pipe(
      tap({
        next: (files) => {
          console.log('✅ Réponse reçue du backend (API):');
          console.log('Nombre de fichiers:', files?.length || 0);
          console.log('Fichiers:', files);
        },
        error: (error) => {
          console.error('❌ Erreur lors de l\'appel API (API):');
          console.error('URL appelée:', url);
          console.error('Status:', error.status);
          console.error('Message:', error.message);
          console.error('Error object:', error);
          console.error('Error text:', error.error);
          console.error('Headers:', error.headers);
        }
      })
    );
  }

  /**
   * Récupérer les fichiers d'un type spécifique
   * @param eventId Identifiant de l'événement
   * @param fileType Type de fichier
   * @returns Observable<EventFileDTO[]>
   */
  getEventFilesByType(eventId: string, fileType: string): Observable<EventFileDTO[]> {
    return this.http.get<EventFileDTO[]>(`${this.baseUrl}/${eventId}/files/type/${fileType}`);
  }

  /**
   * Récupérer toutes les photos de présentation d'un événement
   * @param eventId Identifiant de l'événement
   * @returns Observable<EventFileDTO[]>
   */
  getEventPresentationPhotos(eventId: string): Observable<EventFileDTO[]> {
    return this.http.get<EventFileDTO[]>(`${this.baseUrl}/${eventId}/files/photos`);
  }

  /**
   * Récupérer la photo principale d'un événement
   * @param eventId Identifiant de l'événement
   * @returns Observable<EventFileDTO>
   */
  getMainPhoto(eventId: string): Observable<EventFileDTO> {
    return this.http.get<EventFileDTO>(`${this.baseUrl}/${eventId}/files/main-photo`);
  }

  /**
   * Mettre à jour un fichier d'événement
   * @param eventId Identifiant de l'événement
   * @param fileId Identifiant du fichier
   * @param fileDTO Données du fichier à mettre à jour
   * @returns Observable<EventFileDTO>
   */
  updateEventFile(eventId: string, fileId: string, fileDTO: EventFileDTO): Observable<EventFileDTO> {
    return this.http.put<EventFileDTO>(`${this.baseUrl}/${eventId}/files/${fileId}`, fileDTO);
  }

  /**
   * Définir une photo comme principale
   * @param eventId Identifiant de l'événement
   * @param fileId Identifiant du fichier
   * @returns Observable<EventFileDTO>
   */
  setMainPhoto(eventId: string, fileId: string): Observable<EventFileDTO> {
    return this.http.put<EventFileDTO>(`${this.baseUrl}/${eventId}/files/${fileId}/set-main-photo`, {});
  }

  /**
   * Supprimer un fichier d'événement
   * @param eventId Identifiant de l'événement
   * @param fileId Identifiant du fichier
   * @returns Observable<void>
   */
  deleteEventFile(eventId: string, fileId: string): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/${eventId}/files/${fileId}`);
  }

  /**
   * Supprimer tous les fichiers d'un événement
   * @param eventId Identifiant de l'événement
   * @returns Observable<void>
   */
  deleteAllEventFiles(eventId: string): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/${eventId}/files`);
  }
} 