server:
  port: 8081
  ssl:
    enabled: false

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: ms-event
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/db_rdh}
      database: db_rdh
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# Configuration des fichiers
app:
  file:
    upload-dir: uploads/events
    max-size: 10485760  # 10MB en bytes
    allowed-types: image/jpeg,image/jpg,image/png,image/gif,image/webp,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,video/mp4,audio/mpeg
