/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventLocation { 
    address?: string;
    city?: string;
    postalCode?: string;
    country?: string;
    placeName?: string;
    latitude?: number;
    longitude?: number;
}

