/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventLocation } from './eventLocation';
import { PresenterDTO } from './presenterDTO';
import { EventFileDTO } from './eventFileDTO';


export interface EventDTO { 
    id?: string;
    name?: string;
    date?: string;
    location?: EventLocation;
    description?: string;
    amount?: number;
    numberOfDays?: number;
    presenters?: Array<PresenterDTO>;
    category?: string;
    availableSeats?: number;
    lastRegistrationDate?: string;
    eventType?: string;
    eventStatus?: string;
    free?: boolean;
    files?: Array<EventFileDTO>;
    mainPhotoId?: string;
}

