/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EventFileDTO { 
    id?: string;
    eventId?: string;
    fileName?: string;
    filePath?: string;
    fileExtension?: string;
    fileSize?: number;
    mimeType?: string;
    description?: string;
    uploadDate?: string;
    fileType?: EventFileDTOFileTypeEnum;
    isPresentationPhoto?: boolean;
    isMainPhoto?: boolean;
    accessUrl?: string;
    thumbnailUrl?: string;
}

export enum EventFileDTOFileTypeEnum {
    PRESENTATION_PHOTO = 'PRESENTATION_PHOTO',
    MAIN_PRESENTATION = 'MAIN_PRESENTATION',
    DOCUMENT = 'DOCUMENT',
    VIDEO = 'VIDEO',
    AUDIO = 'AUDIO',
    OTHER = 'OTHER'
} 