/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupEntity { 
    id?: string;
    name?: string;
    type?: string;
    country?: string;
    street?: string;
    city?: string;
    stateOrProvince?: string;
    phone?: string;
    email?: string;
    website?: string;
}

