/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MemberEntity { 
    id?: string;
    lastName?: string;
    firstName?: string;
    gender?: string;
    birthDate?: string;
    profession?: string;
    phoneNumber?: string;
    email?: string;
    address?: string;
    city?: string;
    location?: string;
    photo?: string;
    socialLinks?: Array<string>;
    roles?: Array<string>;
    groupId?: string;
}

