/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventRegistrationDTO { 
    id?: string;
    eventId?: string;
    userId?: string;
    status?: string;
}

