/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventLocation } from './eventLocation';
import { PresenterDTO } from './presenterDTO';
import { EventFileDTO } from './eventFileDTO';


export interface EventDTO { 
    id?: string;
    name?: string;
    date?: string;
    /** Heure de début « HH:mm ». */
    time?: string;
    location?: EventLocation;
    description?: string;
    amount?: number;
    numberOfDays?: number;
    presenters?: Array<PresenterDTO>;
    category?: string;
    availableSeats?: number;
    lastRegistrationDate?: string;
    eventType?: string;
    eventStatus?: string;
    free?: boolean;
    /** « PUBLIC » ou « PRIVATE » : un événement privé n'est visible que par son groupe. */
    visibility?: string;
    /** Groupe organisateur ; renseigné par le serveur d'après le compte connecté. */
    groupId?: string;
    /** Auteur de l'événement ; renseigné par le serveur d'après le compte connecté. */
    createdByEmail?: string;
    /** Fichiers joints, renvoyés par `/events/with-files`. */
    files?: Array<EventFileDTO>;
    /** Identifiant du fichier servant de visuel principal. */
    mainPhotoId?: string;
    /**
     * Champs additifs — paiement. `stripeAccountId`/`stripeAccountStatus` : compte
     * Stripe propre à cet événement (override, sinon celui du groupe organisateur).
     * `applicationFeeEnabled` : `null`/absent hérite du réglage du groupe ; réservé
     * au super admin. Voir `create-event.component.ts`.
     */
    stripeAccountId?: string | null;
    stripeAccountStatus?: 'none' | 'pending' | 'active' | 'restricted';
    applicationFeeEnabled?: boolean | null;
}

