/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupEntity { 
    id?: string;
    name?: string;
    type?: string;
    country?: string;
    street?: string;
    city?: string;
    stateOrProvince?: string;
    phone?: string;
    email?: string;
    website?: string;
    /**
     * Modules attribués au groupe : « EVENTS », « MEMBERS », ou les deux.
     * Ajouté après la génération : le serveur le renvoie toujours explicitement.
     */
    features?: string[];
    /**
     * Absent ou vrai : les membres du groupe voient aussi les événements
     * publics des autres groupes. `false` referme le catalogue à ce que ce
     * groupe organise lui-même.
     */
    showPublicCatalog?: boolean;
    /** Champs additifs — demande de création par un membre, et sa décision. */
    status?: 'PENDING' | 'APPROVED' | 'REJECTED';
    requestedByEmail?: string | null;
    requestedAt?: string | null;
    decidedByEmail?: string | null;
    decidedAt?: string | null;
    rejectionReason?: string | null;
}

