/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class FileControllerService {
  private baseUrl = '/api/v1/files';

  constructor(private http: HttpClient) { }

  /**
   * Télécharger une photo d'événement
   * @param eventId Identifiant de l'événement
   * @param filename Nom du fichier
   * @returns Observable<Blob>
   */
  downloadFile(eventId: string, filename: string): Observable<Blob> {
    return this.http.get(`${this.baseUrl}/events/${eventId}/${filename}`, {
      responseType: 'blob'
    });
  }

  /**
   * Télécharger un thumbnail
   * @param eventId Identifiant de l'événement
   * @param filename Nom du fichier
   * @returns Observable<Blob>
   */
  downloadThumbnail(eventId: string, filename: string): Observable<Blob> {
    return this.http.get(`${this.baseUrl}/events/${eventId}/thumbnails/${filename}`, {
      responseType: 'blob'
    });
  }

  /**
   * Obtenir l'URL d'accès à un fichier
   * @param eventId Identifiant de l'événement
   * @param filename Nom du fichier
   * @returns string
   */
  getFileUrl(eventId: string, filename: string): string {
    return `${this.baseUrl}/events/${eventId}/${filename}`;
  }

  /**
   * Obtenir l'URL d'accès à un thumbnail
   * @param eventId Identifiant de l'événement
   * @param filename Nom du fichier
   * @returns string
   */
  getThumbnailUrl(eventId: string, filename: string): string {
    return `${this.baseUrl}/events/${eventId}/thumbnails/${filename}`;
  }
} 