import { IonicConfig } from '@ionic/angular';

export const mobileConfig: IonicConfig = {
  mode: 'ios', // Mode iOS par défaut
  backButtonText: 'Retour',
  backButtonIcon: 'arrow-back-outline',
  spinner: 'crescent',
  loadingSpinner: 'crescent',
  menuType: 'overlay',
  animated: true,
  rippleEffect: true,
  hardwareBackButton: true,
  statusBarStyle: 'default',
  statusBarBackgroundColor: '#ED5F00',
  tabButtonLayout: 'icon-top',
  tabBarPlacement: 'bottom',
  tabBarHighlight: true,
  tabBarColor: '#ED5F00',
  tabBarStyle: 'default',
  tabBarPosition: 'bottom',
  tabBarLayout: 'icon-top',
  tabBarJustify: 'space-around',
  tabBarBackground: 'white',
  tabBarBorder: '1px solid #e0e0e0',
  tabBarShadow: '0 2px 4px rgba(0,0,0,0.1)',
  tabBarTranslucent: false,
  tabBarHideOnScroll: false,
  tabBarScrollable: false,
  tabBarScrollableThreshold: 0,
  tabBarScrollableDirection: 'horizontal',
  tabBarScrollableWidth: 'auto',
  tabBarScrollableHeight: 'auto',
  tabBarScrollablePadding: '0',
  tabBarScrollableMargin: '0',
  tabBarScrollableBorder: 'none',
  tabBarScrollableShadow: 'none',
  tabBarScrollableBackground: 'transparent',
  tabBarScrollableOpacity: 1,
  tabBarScrollableTransform: 'none',
  tabBarScrollableTransition: 'none',
  tabBarScrollableAnimation: 'none',
  tabBarScrollableDuration: 300,
  tabBarScrollableEasing: 'ease-in-out',
  tabBarScrollableDelay: 0,
  tabBarScrollableOffset: 0,
  tabBarScrollableThreshold: 0,
  tabBarScrollableDirection: 'horizontal',
  tabBarScrollableWidth: 'auto',
  tabBarScrollableHeight: 'auto',
  tabBarScrollablePadding: '0',
  tabBarScrollableMargin: '0',
  tabBarScrollableBorder: 'none',
  tabBarScrollableShadow: 'none',
  tabBarScrollableBackground: 'transparent',
  tabBarScrollableOpacity: 1,
  tabBarScrollableTransform: 'none',
  tabBarScrollableTransition: 'none',
  tabBarScrollableAnimation: 'none',
  tabBarScrollableDuration: 300,
  tabBarScrollableEasing: 'ease-in-out',
  tabBarScrollableDelay: 0,
  tabBarScrollableOffset: 0
};